export const MEB_CLUBS: string[] = [
    "Afet Hazırlık Kulübü",
    "Bilim-Fen ve Teknoloji Kulübü",
    "Bilinçli Tüketici Kulübü",
    "Bilişim ve İnternet Kulübü",
    "Çevre Koruma Kulübü",
    "Çocuk Hakları Kulübü",
    "Değerler Kulübü",
    "Demokrasi, İnsan Hakları ve Yurttaşlık Kulübü",
    "Denizcilik Kulübü",
    "Enerji Verimliliği Kulübü",
    "Engellilerle Dayanışma Kulübü",
    "eTwinning Kulübü",
    "Felsefe veya Düşünce Eğitimi Kulübü",
    "Fotoğrafçılık Kulübü",
    "Geleneksel Sanatlar Kulübü",
    "Gezi,Tanıtma ve Turizm Kulübü",
    "Girişimcilik Kulübü",
    "Görsel Sanatlar Kulübü",
    "Halk Oyunları Kulübü",
    "Havacılık Kulübü",
    "Hayvanları Sevme ve Koruma Kulübü",
    "Hoş Sadâ Musîki Kulübü",
    "Sağlık ve Güvenlik Kulübü",
    "İzcilik Kulübü",
    "Kızılay ve Kan Bağışı Kulübü",
    "Kişisel Verileri Koruma Kulübü",
    "Kooperatifçilik Kulübü",
    "Kültür ve Edebiyat Kulübü",
    "Kültür ve Tabiat Varlıklarını Koruma ve Okul Müzesi Kulübü",
    "Kütüphanecilik Kulübü",
    "Meslek Tanıtma Kulübü",
    "Mesleki Tatbikat Kulübü",
    "MUN (Model Birleşmiş Milletler) Kulübü",
    "Münazara Kulübü",
    "Müzik Kulübü",
    "Örnek ve Öncü Şahsiyetler Tanıtım Kulübü",
    "Pulculuk Kulübü",
    "Sağlık, Temizlik ve Beslenme Kulübü",
    "Satranç Kulübü",
    "Şehir ve Medeniyet Kulübü",
    "Şiir ve Tefekkür Kulübü",
    "Sosyal Yardımlaşma ve Dayanışma, Çocuk Esirgeme Kulübü",
    "Sosyal Medya Kulübü",
    "Spor Kulübü",
    "Siberay Kulübü",
    "Tiyatro Kulübü",
    "Trafik Güvenliği ve İlkyardım Kulübü",
    "Yabancı Diller Kulübü",
    "Yayın ve İletişim Kulübü",
    "Yeşilay Kulübü",
    "Yeşili Koruma Kulübü",
    "Zekâ Oyunları Kulübü"
  ];
  