export const HIGH_SCHOOL_LESSONS: string[] = [
    "Türk Dili ve Edebiyatı",
    "Matematik",
    "Fizik",
    "Kimya",
    "Biyoloji",
    "Tarih",
    "Coğrafya",
    "Felsefe",
    "İngilizce",
    "Almanca",
    "Fransızca",
    "Din Kültürü ve Ahlak Bilgisi",
    "Beden Eğitimi ve Spor",
    "Görsel Sanatlar",
    "Müzik",
    "Sağlık Bilgisi ve Trafik Kültürü",
    "Psikoloji",
    "Sosyoloji",
    "Mantık",
    "Girişimcilik",
    "Bilgi ve İletişim Teknolojisi",
    "Mesleki Gelişim Atölyesi",
    // Alan Dersleri
    "Makine Teknolojisi",
    "Elektrik-Elektronik Teknolojisi",
    "Bilişim Teknolojileri",
    "Metal Teknolojisi",
    "Mobilya ve İç Mekan Tasarımı",
    "Motorlu Araçlar Teknolojisi",
    "Tesisat Teknolojisi ve İklimlendirme",
    "Çocuk Gelişimi ve Eğitimi",
    "Grafik ve Fotoğraf",
    "Güzellik ve Saç Bakım Hizmetleri",
    "Halkla İlişkiler ve Organizasyon Hizmetleri",
    "Hasta ve Yaşlı Hizmetleri",
    "Muhasebe ve Finansman",
    "Pazarlama ve Perakende",
    "Ulaştırma Hizmetleri",
    "Yiyecek İçecek Hizmetleri",
    "Konaklama ve Seyahat Hizmetleri",
  ];
  