// This file is automatically generated. Do not edit.
// If you want to switch to a different Firebase project, select
// "Change Firebase Project" from the "Firebase" menu in VS Code.
export const firebaseConfig = {
  "apiKey": "API_KEY",
  "authDomain": "AUTH_DOMAIN",
  "projectId": "PROJECT_ID",
  "storageBucket": "STORAGE_BUCKET",
  "messagingSenderId": "MESSAGING_SENDER_ID",
  "appId": "APP_ID",
  "measurementId": "MEASUREMENT_ID"
};
